### ISSUE TITLE
Precisa ser >= 18, pq 18 anos já é maior.

### ISSUE THREAD

**Issue by ziin** [marcuspaulo/gonode-desafio-1#1]
https://github.com/marcuspaulo/gonode-desafio-1/blob/2122db965f9d8ce995874347fe7068dd067f7521/index.js#L39

**Comment by marcuspaulo** [comment]
> [gonode-desafio-1/index.js](https://github.com/marcuspaulo/gonode-desafio-1/blob/2122db965f9d8ce995874347fe7068dd067f7521/index.js#L39)
> 
> Line 39 in [2122db9](/marcuspaulo/gonode-desafio-1/commit/2122db965f9d8ce995874347fe7068dd067f7521)
> 
>  if (inputAge > 18) {

Muito obrigado @ziin , o código está ajustado e "commitado".
